config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    namespace :admin do
      root "static_pages#home"
      resources :games, only: [:new, :create, :edit, :update, :destroy]
      resources :genres, only: [:new, :create]
      resources :users, only: [:index, :update]
    end
    delete "/logout", to: "sessions#destroy"
    get  "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    get "sessions/new"
    post "/login", to: "sessions#create"
    post "/signup", to: "users#create"
    resources :games, only: [:index, :show]
    resources :users, only: [:show, :edit, :update]
    resources :reviews, only: [:create, :edit, :update, :destroy]
    resources :replies, only: [:create, :edit, :update, :destroy]
    resources :wishlists, only: [:index, :create, :destroy]
    get "static_pages/home"
    root "static_pages#home"
  end
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :user
  belongs_to :review

  validates :content, presence: true
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_action :find_reply, only: [:edit, :destroy]

  def create
    @reply = Reply.new reply_params
    if @reply.save
      @comment = Review.new
      @new_reply = Review.new
      respond_to do |format|
        format.js
      end
    else
      respond_to do |format|
        format.js { render "create_failed" }
      end
    end
  end

  def edit
    @new_reply = @reply
    @review = @reply.review
  end

  def update
    @reply = Reply.find_by id: params[:reply][:reply_id]
    if @reply && @reply.update_attributes(reply_params)
      respond_to do |format|
        format.js
      end
    else
      respond_to do |format|
        format.js { render "create_failed" }
      end
    end
  end

  def destroy
    @reply.destroy unless @reply.nil?
  end

  private

  def find_reply
    @reply = Reply.find_by id: params[:id]
  end

  def reply_params
    params.require(:reply).permit :content, :user_id, :review_id
  end
end

app/views/replies/_reply.html.erb
<li>
  <div id="<%= "reply_#{reply.id}" %>">
    <div style="margin-bottom: 5px;">
      <strong style="cursor: pointer;"><%= reply.user.nick_name %></strong>
    </div>
    <div style="white-space: pre-line;"><%= reply.content %></div>
    <% if reply.user == current_user %>
      <%= link_to "Edit", edit_reply_path(reply), remote: true %>
      <%= link_to "Delete", reply_path(reply), method: :delete, remote: true, style: "margin-left: 5px;" %>
    <% end %>
  </div>
</li>

app/views/replies/_reply_form.html.erb
<li id="<%= "reply_form_#{review.id}_#{@new_reply.id}" %>">
  <div class="uk-margin" uk-margin style="margin: 10px 0 0 20px;">
    <%= form_for @new_reply, remote: true do |f| %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.hidden_field :review_id, value: review.id %>
      <%= f.hidden_field :reply_id, value: @new_reply.id %>

      <div class="uk-margin" style="margin-bottom: 10px; width: 50%; display: flex;">
        <%= f.text_area :content, id: "reply_#{review.id}_text_field", class: "uk-textarea", rows: 2, placeholder: "Enter your reply" %>
        <%= f.submit "Reply", class: "uk-button uk-button-default", style: "font-size:1em" %>
      </div>
    <% end %>
  </div>
</li>

app/views/replies/create.js.erb
$("<%= j render(@reply) %>").insertBefore("#reply_form_" + <%= @reply.review.id %> + "_");
$("#reply_" + <%= @reply.review.id %> +"_text_field").val("");
$("#reply_" + <%= @reply.review.id %> +"_text_field").attr("placeholder", "");

app/views/replies/create_failed.js.erb
$("#reply_" + <%= @reply.review.id %> + "_text_field").attr("placeholder", "Nội dung không được để trống");

app/views/replies/destroy.js.erb
$("#reply_" + <%= @reply.id %>).parent().remove();

app/views/replies/edit.js.erb
$("#reply_" + <%= @reply.id %>).after("<%= j render("replies/reply_form", review: @review) %>");
$("#reply_" + <%= @reply.id %>).hide();

app/views/replies/update.js.erb
$("#reply_form_" + <%= @reply.review.id %> + "_" + <%= @reply.id %>).remove();
$("#reply_" + <%= @reply.id %>).html("<li><%= @reply.content %></li>");
$("#reply_" + <%= @reply.id %>).show();