config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    namespace :admin do
      root "static_pages#home"
      resources :games, only: [:new, :create, :edit, :update, :destroy]
      resources :genres, only: [:new, :create]
      resources :users, only: [:index, :update]
    end
    delete "/logout", to: "sessions#destroy"
    get  "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    get "sessions/new"
    post "/login", to: "sessions#create"
    post "/signup", to: "users#create"
    resources :games, only: [:index, :show]
    resources :users, only: [:show, :edit, :update]
    resources :reviews, only: [:create, :edit, :update, :destroy]
    resources :replies, only: [:create, :edit, :update, :destroy]
    resources :wishlists, only: [:index, :create, :destroy]
    get "static_pages/home"
    root "static_pages#home"
  end
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :game_genres, dependent: :destroy
  has_many :genres, through: :game_genres
  has_many :screenshots, dependent: :destroy
  has_many :trailers, dependent: :destroy
  has_many :wishlists
  has_many :users, through: :wishlists
  belongs_to :user
  accepts_nested_attributes_for :trailers, allow_destroy: true
  accepts_nested_attributes_for :screenshots, allow_destroy: true, reject_if: proc { |attributes| attributes['picture'].blank? }
  mount_uploader :picture, PictureUploader

  validates :name, presence: true, uniqueness: {case_sensitive: false}
  validates :details, presence: true
  validates :price, presence: true
  validates :picture, presence: true

  scope :top_rated, ->(num) {order(score: :desc).limit(num)}
  scope :new_arrivals, ->(num) {order(created_at: :desc).limit(num)}
  scope :best_sellers, ->(num) {order(download_count: :desc).limit(num)}

  def calculate_average_score
    if reviews.empty?
      update_attributes(score: 0)
    else
      update_attributes(score: reviews.average(:score).round(2))
    end
  end
end

app/controllers/admin/games_controller.rb
class Admin::GamesController < ApplicationController
  before_action :admin_required
  before_action :find_game, only: [:edit, :update, :destroy]
  before_action :correct_maker?, only: [:edit, :update, :destroy]

  def edit
    @game_genres = @game.genres.map(&:genre)
    @genres = Genre.all.map(&:genre)
  end

  def update
    if @game.update_attributes game_params
      unless params[:genre].nil?
        @game.genres.clear
        genres = Genre.all.map(&:genre)
        params[:genre].each do |genre, isChecked|
          if isChecked.to_i == 1
            g = Genre.find_by genre: genre
            @game.game_genres.create!(genre_id: g.id)
          end
        end
      end
      flash[:success] = t "flash.updated"
      redirect_to @game
    else
      render :edit
    end
  end

  def new
    @game = Game.new
    @genres = Genre.all.map(&:genre)
  end

  def create
    @game = Game.new game_params
    @game.user = current_user
    if @game.save
      unless params[:screenshots].nil?
        params[:screenshots]['picture'].each do |picture|
          @game.screenshots.create!(picture: picture)
        end
      end
      unless params[:genre].nil?
        genres = Genre.all.map(&:genre)
        params[:genre].each do |genre, isChecked|
          if isChecked.to_i == 1
            g = Genre.find_by genre: genre
            @game.game_genres.create!(genre_id: g.id)
          end
        end
      end
      unless params[:game][:trailer].nil?
        params[:game][:trailer][:trailer].split("\n").each do |link|
          @game.trailers.create!(youtube_link: link)
        end
      end
      flash[:success] = t "flash.add_game_success"
      redirect_to @game
    else
      @genres = Genre.all.map(&:genre)
      flash[:danger] = t "flash.add_game_failed"
      render :new
    end
  end

  def destroy
    if @game.destroy
      flash[:success] = t "flash.delete_game_success"
      redirect_to root_url
    else
      flash[:danger] = t "flash.delete_game_failed"
      redirect_to @game
    end
  end

  private

  def correct_maker?
    current_user.make @game
  end

  def find_game
    @game = Game.find_by id: params[:id]
  end

  def game_params
    params.require(:game).permit :name, :details, :price, :picture, screenshots_attributes: [:id, :game_id, :picture],
      trailers_attributes: [:id, :game_id, :youtube_link]
  end

  def admin_required
    return if current_user && (current_user.admin? || current_user.maker?)
    redirect_to root_url
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = @q.result.includes(:genres).paginate(:page => params[:page], :per_page => 9)
    @genres = Genre.all.map(&:genre)
  end

  def show
    @game = Game.find_by id: params[:id]
    if current_user.nil?
      @my_review = nil
      @other_reviews = @game.reviews
    else
      @my_review = @game.reviews.find_by user_id: current_user.id
      @other_reviews = @game.reviews.all_except current_user
    end
    @comment = unless current_user.nil?
                  @my_review || Review.new
               else
                  Review.new
               end
    @new_reply = Reply.new
  end

  private

  def game_params
    params.require(:game).permit :name, :details, :price, :picture, screenshots_attributes: [:id, :game_id, :picture]
  end
end

app/helpers/games_helper.rb
module GamesHelper
  YOUTUBE_SHORT = %r{youtu\.be\/([^\?]*)}
  YOUTUBE_LONG = %r{^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*}

  def youtube_embed youtube_url
    return unless youtube_url
    matches = YOUTUBE_SHORT.match youtube_url
    if matches
      youtube_id = matches[1]
    else
      matches = YOUTUBE_LONG.match youtube_url
      youtube_id = matches[5]
    end
    content_tag :iframe, "", src: "https://www.youtube.com/embed/#{youtube_id}",
      width: 500,
      height: 300, frameborder: 0,
      allow: "autoplay; encrypted-media", allowfullscreen: true
  end
end

app/views/admin/games/_form.html.erb
<%= form_for @game, url: yield(:url), class: "uk-form-stacked" do |f| %>
  <div class="uk-margin">
    <div class="uk-form-controls">
      <%= render "shared/error_messages", object: @game %>
    </div>
  </div>

  <div class="uk-margin">
    <%= f.label :name, t("games.name") %>
    <div class="uk-form-controls">
      <div class="uk-inline">
        <span class="uk-form-icon" uk-icon="icon: nut"></span>
        <%= f.text_field :name, class: "uk-input uk-form-width-large" %>
      </div>
    </div>
  </div>

  <div class="uk-margin uk-grid-small uk-child-width-auto uk-grid">
    <label style="display: block; width: 100%; margin-bottom: 5px;">Genre</label>
    <% @genres.each do |genre| %>
      <label>
        <%= check_box :genre, genre, class: "uk-checkbox", style: "margin: -2px 0 0;" %>
        <%= genre %>
      </label>
    <% end %>
  </div>

  <div class="uk-margin">
    <%= f.label :details, t("games.details") %>
    <div class="uk-form-controls">
      <%= f.text_area :details, class: "uk-textarea uk-form-width-large", rows: 5 %>
    </div>
  </div>

  <div class="uk-margin">
    <%= f.label :price, t("games.price") %>
    <div class="uk-form-controls">
      <div class="uk-inline">
        <span class="uk-form-icon" uk-icon="icon: cart"></span>
        <%= f.number_field :price, class: "uk-input uk-form-width-large" %>
      </div>
    </div>
  </div>

  <div class="uk-margin">
    <%= f.label :trailer, t("games.trailers") %>
    <%= f.fields_for :trailer do |p| %>
      <div class="uk-form-controls">
        <%= p.text_area :trailer, placeholder: "Youtube link, separated by line breaks", class: "uk-textarea uk-form-width-large", rows: 2 %>
      </div>
    <% end %>
  </div>

  <span class="picture">
    <label>Cover</label>
    <%= f.file_field :picture %>
  </span>
  <br>
  <%= f.fields_for :screenshot do |p| %>
    <div class="field">
      <%= p.label :screenshot %><br>
      <%= p.file_field :screenshot, multiple: true, name: "screenshots[picture][]" %>
    </div>
  <% end %>

  <div class="uk-margin">
    <%= f.submit yield(:button_text), class: "uk-button uk-button-primary", style: "font-size:1em" %>
  </div>
<% end %>

app/views/admin/games/_update_form.html.erb
<%= form_for @game, url: yield(:url), class: "uk-form-stacked" do |f| %>
  <div class="uk-margin">
    <div class="uk-form-controls">
      <%= render "shared/error_messages", object: @game %>
    </div>
  </div>
  <div class="uk-margin">
    <%= f.label :name, t("games.name") %>
    <div class="uk-form-controls">
      <div class="uk-inline">
        <span class="uk-form-icon" uk-icon="icon: user"></span>
        <%= f.text_field :name, class: "uk-input uk-form-width-large" %>
      </div>
    </div>
  </div>
  <% @genres.each do |genre| %>
    <div>
      <% if @game_genres.include? genre %>
        <%= check_box :genre, genre, {checked: true} %>
      <% else %>
        <%= check_box :genre, genre %>
      <% end %>
      <%= f.label :genre, genre %>
    </div>
  <% end %>

  <div class="uk-margin">
    <%= f.label :details, t("games.details") %>
    <div class="uk-form-controls">
      <div class="uk-inline">
        <span class="uk-form-icon" uk-icon="icon: info"></span>
        <%= f.text_field :details, class: "uk-input uk-form-width-large" %>
      </div>
    </div>
  </div>
  <div class="uk-margin">
    <%= f.label :price, t("games.price") %>
    <div class="uk-form-controls">
      <div class="uk-inline">
        <span class="uk-form-icon" uk-icon="icon: lock"></span>
        <%= f.number_field :price, class: "uk-input uk-form-width-large" %>
      </div>
    </div>
  </div>

  <div class="uk-margin">
    <%= f.submit yield(:button_text), class: "uk-button uk-button-primary", style: "font-size:1em" %>
  </div>
<% end %>

app/views/admin/games/edit.html.erb
<% provide :title, t("games.update_game") %>
<% provide :button_text, t("games.edit.update") %>
<% provide :url, admin_game_path(@game) %>

<div class="uk-card uk-card-body" style="color: #fff;">
  <div class="uk-card-title">
    <h1><%= t "games.add_game" %></h1>
  </div>
  <div class="uk-card-body">
    <%= render "update_form" %>
  </div>
</div>

app/views/admin/games/new.html.erb
<% provide :title, t("games.add_game") %>
<% provide :button_text, t("games.new.add") %>
<% provide :url, admin_games_path %>

<div class="uk-card uk-card-body" style="color: #fff;">
  <div class="uk-card-title">
    <h1><%= t "games.add_game" %></h1>
  </div>
  <div class="uk-card-body">
    <%= render "form" %>
  </div>
</div>