config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    namespace :admin do
      root "static_pages#home"
      resources :games, only: [:new, :create, :edit, :update, :destroy]
      resources :genres, only: [:new, :create]
      resources :users, only: [:index, :update]
    end
    delete "/logout", to: "sessions#destroy"
    get  "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    get "sessions/new"
    post "/login", to: "sessions#create"
    post "/signup", to: "users#create"
    resources :games, only: [:index, :show]
    resources :users, only: [:show, :edit, :update]
    resources :reviews, only: [:create, :edit, :update, :destroy]
    resources :replies, only: [:create, :edit, :update, :destroy]
    resources :wishlists, only: [:index, :create, :destroy]
    get "static_pages/home"
    root "static_pages#home"
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  has_many :wishlists
  has_many :games, through: :wishlists
  enum user_type: [:member, :admin, :maker]
  mount_uploader :picture, PictureUploader
  attr_reader :remember_token

  VALID_EMAIL_REGEX = /\A[\w.\-]+@[a-z+\d\-.]+\.+[a-z]+\z/i
  validates :nick_name, presence: true,
    length: {maximum: Settings.name_max_length}
  validates :email, presence: true,
    length: {maximum: Settings.email_max_length},
    format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :password, presence: true, allow_nil: true,
    length: {minimum: Settings.pass_min_length}
   before_save :email_downcase
  has_secure_password

  scope :except_admin, ->() {where.not user_type: 1}

  def remember
    @remember_token = User.new_token
    update_attributes remember_digest: User.digest(remember_token)
  end

  def authenticated? remember_token
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password? remember_token
  end

  def forget
    update_attributes remember_digest: nil
  end

  class << self
    def digest string
      cost = if ActiveModel::SecurePassword.min_cost
               BCrypt::Engine::MIN_COST
             else
               BCrypt::Engine.cost
             end
      BCrypt::Password.create string, cost: cost
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def current_user? current_user
    self == current_user
  end

  def make game
    self == game.user
  end

  private

  def email_downcase
    self.email = email.downcase
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.except_admin
  end

  def update
    respond_to do |format|
      @user = User.find_by id: params[:id]
      if @user&.maker?
        @user.member!
        format.js{render "admin/users/degrade"}
      elsif @user&.member?
        @user.maker!
        format.js{render "admin/users/upgrade"}
      else
        format.html
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update]
  before_action :correct_user, only: [:edit, :update]

  def show
    @reviews = @user.reviews.paginate(:page => params[:page], :per_page => 9)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      log_in @user
      flash[:success] = t "flash.welcome"
      redirect_to root_path
    else
      flash[:danger] = t "flash.create_user_failed"
      render :new
    end
  end

  def edit; end

  def update
    if @user.update_attributes user_params
      flash[:success] = t "flash.updated"
      redirect_to @user
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit :nick_name, :email, :password,
      :password_confirmation, :picture
  end

  def correct_user
    redirect_to root_url unless @user.current_user? current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user
    gravatar_id = Digest::MD5.hexdigest user.email.downcase
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag gravatar_url, alt: user.nick_name, class: "gravatar"
  end

  def had_comment_in game
    current_user.reviews.find_by game_id: game.id
  end
end

app/views/users/_form.html.erb
<%= form_for @user, url: yield(:url), class: "uk-form-stacked" do |f| %>
  <div class="uk-margin">
    <div class="uk-form-controls">
      <%= render "shared/error_messages", object: @user %>
    </div>
  </div>
  <div class="uk-margin">
    <%= f.label :nick_name, t("users.name") %>
    <div class="uk-form-controls">
      <div class="uk-inline">
        <span class="uk-form-icon" uk-icon="icon: user"></span>
        <%= f.text_field :nick_name, class: "uk-input uk-form-width-large" %>
      </div>
    </div>
  </div>
  <div class="uk-margin">
    <%= f.label :email, t("users.email") %>
    <div class="uk-form-controls">
      <div class="uk-inline">
        <span class="uk-form-icon" uk-icon="icon: mail"></span>
        <%= f.email_field :email, class: "uk-input uk-form-width-large" %>
      </div>
    </div>
  </div>
  <div class="uk-margin">
    <%= f.label :password, t("users.password") %>
    <div class="uk-form-controls">
      <div class="uk-inline">
        <span class="uk-form-icon" uk-icon="icon: lock"></span>
        <%= f.password_field :password, class: "uk-input uk-form-width-large" %>
      </div>
    </div>
  </div>
  <div class="uk-margin">
    <%= f.label :password_confirmation, t("users.confirm")%>
    <div class="uk-form-controls">
      <div class="uk-inline">
        <span class="uk-form-icon" uk-icon="icon: lock"></span>
        <%= f.password_field :password_confirmation, class: "uk-input uk-form-width-large" %>
      </div>
    </div>
  </div>
  <div class="uk-margin">
    <%= f.submit yield(:button_text), class: "uk-button uk-button-primary", style: "font-size:1em" %>
  </div>
<% end %>

app/views/users/_reply_history.html.erb
<li>
  <div id="<%= "reply_#{reply.id}" %>">
    <strong style="margin-right: 18px; cursor: pointer;"><%= reply.user.nick_name %></strong>
    <%= reply.content %>
  </div>
</li>

app/views/users/_review_history.erb
<li>
  <span style="margin-right: 18px;">
    <%= link_to review.game.name, game_path(review.game) %>
  </span>
  <%= review.content %>
  <div class="wthreeratingaits review">
    <%= render "shared/star", score: review.score %>
  </div>
  <ul class="uk-list uk-list-divider">
    <%= render review.reply %>
  </ul>
</li>

app/views/users/edit.html.erb
<% provide :title, t(".edit") %>
<% provide :button_text, t(".save") %>
<% provide :url, user_path(current_user) %>

<!-- fake, ai sua lai css ho cai nhe -->
  <br>
  <br>
  <br>
<div class="uk-card uk-card-body" style="color: #fff;">
  <div class="uk-card-title">
    <h1><%= t ".update" %></h1>
  </div>
  <div class="uk-card-body">
    <%= render "form" %>
    <div style="width: 100px">
      <%= gravatar_for @user %>
    </div>
    <%= link_to t(".change"), "http://gravatar.com/emails",
    target:"_blank", rel:"noopener" %>
  </div>
</div>

app/views/users/new.html.erb
<% provide :title, t(".signup") %>
<% provide :button_text, t(".signup-btn") %>
<% provide :url, signup_path %>

<div class="uk-card uk-card-body" style="color: #fff;">
  <div class="uk-card-title">
    <div><%= t ".signup" %></div>
  </div>
  <div class="uk-card-body">
    <%= render "form" %>
  </div>
  <p><%= t ".have_acc" %> <%= link_to t(".login"), login_path %></p>
</div>

app/views/users/show.html.erb
<div class="container" style="color: white; padding-top: 100px; padding-bottom: 100px;" >
  <div class="row">
    <div class="col-sm-10"><h1><%= t ".profile"%></h1></div>
  </div>
  <div class="row">
    <div class="col-sm-3"><!--left col-->
      <div class="text-center">
        <% if (@user.picture && @user.picture.url) %>
          <%= image_tag(@user.picture.url, alt: "avatar") %>
        <% else %>
          <%= image_tag("/uploads/user/picture/default_avatar.jpg", alt: "avatar") %>
        <% end %>
        <%if logged_in? %>
          <br><br>
          <h5>Upload a different photo...</h5>
          <br>
          <%= form_for @user, html: {id: "upload_avatar_form"} do |f| %>
            <%= f.file_field :picture, id: "upload_avatar" %>
          <% end %>
        <% end %>

      </div></hr><br>

      <div class="panel panel-default">
        <%if logged_in? %>
          <div class="panel-heading"><i class="fa fa-link fa-1x"></i> <%= link_to t(".edit"), edit_user_path(current_user) %> </div>
        <% end %>
        <div class="panel-heading"><i class="fa fa-heart fa-1x"></i> <%= link_to t(".wishlist"), wishlists_path %> </div>
      </div>
    </div><!--/col-3-->
    <div class="col-sm-9">
      <div class="tab-content">
        <div class="tab-pane active" id="home">
          <hr>
          <div class="col-xs-6">
            <label for="first_name"><h4><%= t "users.name"%>: </h4></label>
            <label><h4><%= @user.nick_name%></h4></label>
          </div>
          <div class="col-xs-6">
            <label for="first_name"><h4><%= t "users.role"%>: </h4></label>
            <label><h4><%= @user.user_type%></h4></label>
          </div>
          <div class="col-xs-6">
            <label for="email"><h4><%= t "users.email"%>: </h4></label>
            <label><h4><%= @user.email%></h4></label>
          </div>
        </div>
      </div><!--/tab-content-->
      <br><br><br><br>
      <h1><%= t ".review_history" %></h1>
      <br>
      <%= will_paginate @reviews %>
      <br>
      <ul class="uk-list uk-list-divider">
        <% @reviews.each do |review| %>
          <%= render "review_history", review: review %>
        <% end %>
      </ul>
      <%= will_paginate @reviews %>
    </div><!--/col-9-->
  </div>
</div><!--/row-->

<script type="text/javascript">
  $("#upload_avatar").on('change', function() {
    $("#upload_avatar_form").submit();
  });
</script>