config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    namespace :admin do
      root "static_pages#home"
      resources :games, only: [:new, :create, :edit, :update, :destroy]
      resources :genres, only: [:new, :create]
      resources :users, only: [:index, :update]
    end
    delete "/logout", to: "sessions#destroy"
    get  "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    get "sessions/new"
    post "/login", to: "sessions#create"
    post "/signup", to: "users#create"
    resources :games, only: [:index, :show]
    resources :users, only: [:show, :edit, :update]
    resources :reviews, only: [:create, :edit, :update, :destroy]
    resources :replies, only: [:create, :edit, :update, :destroy]
    resources :wishlists, only: [:index, :create, :destroy]
    get "static_pages/home"
    root "static_pages#home"
  end
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :game_genres, dependent: :destroy
  has_many :genres, through: :game_genres
  has_many :screenshots, dependent: :destroy
  has_many :trailers, dependent: :destroy
  has_many :wishlists
  has_many :users, through: :wishlists
  belongs_to :user
  accepts_nested_attributes_for :trailers, allow_destroy: true
  accepts_nested_attributes_for :screenshots, allow_destroy: true, reject_if: proc { |attributes| attributes['picture'].blank? }
  mount_uploader :picture, PictureUploader

  validates :name, presence: true, uniqueness: {case_sensitive: false}
  validates :details, presence: true
  validates :price, presence: true
  validates :picture, presence: true

  scope :top_rated, ->(num) {order(score: :desc).limit(num)}
  scope :new_arrivals, ->(num) {order(created_at: :desc).limit(num)}
  scope :best_sellers, ->(num) {order(download_count: :desc).limit(num)}

  def calculate_average_score
    if reviews.empty?
      update_attributes(score: 0)
    else
      update_attributes(score: reviews.average(:score).round(2))
    end
  end
end

app/controllers/admin/games_controller.rb
class Admin::GamesController < ApplicationController
  before_action :admin_required
  before_action :find_game, only: [:edit, :update, :destroy]
  before_action :correct_maker?, only: [:edit, :update, :destroy]

  def edit
    @game_genres = @game.genres.map(&:genre)
    @genres = Genre.all.map(&:genre)
  end

  def update
    if @game.update_attributes game_params
      unless params[:genre].nil?
        @game.genres.clear
        genres = Genre.all.map(&:genre)
        params[:genre].each do |genre, isChecked|
          if isChecked.to_i == 1
            g = Genre.find_by genre: genre
            @game.game_genres.create!(genre_id: g.id)
          end
        end
      end
      flash[:success] = t "flash.updated"
      redirect_to @game
    else
      render :edit
    end
  end

  def new
    @game = Game.new
    @genres = Genre.all.map(&:genre)
  end

  def create
    @game = Game.new game_params
    @game.user = current_user
    if @game.save
      unless params[:screenshots].nil?
        params[:screenshots]['picture'].each do |picture|
          @game.screenshots.create!(picture: picture)
        end
      end
      unless params[:genre].nil?
        genres = Genre.all.map(&:genre)
        params[:genre].each do |genre, isChecked|
          if isChecked.to_i == 1
            g = Genre.find_by genre: genre
            @game.game_genres.create!(genre_id: g.id)
          end
        end
      end
      unless params[:game][:trailer].nil?
        params[:game][:trailer][:trailer].split("\n").each do |link|
          @game.trailers.create!(youtube_link: link)
        end
      end
      flash[:success] = t "flash.add_game_success"
      redirect_to @game
    else
      @genres = Genre.all.map(&:genre)
      flash[:danger] = t "flash.add_game_failed"
      render :new
    end
  end

  def destroy
    if @game.destroy
      flash[:success] = t "flash.delete_game_success"
      redirect_to root_url
    else
      flash[:danger] = t "flash.delete_game_failed"
      redirect_to @game
    end
  end

  private

  def correct_maker?
    current_user.make @game
  end

  def find_game
    @game = Game.find_by id: params[:id]
  end

  def game_params
    params.require(:game).permit :name, :details, :price, :picture, screenshots_attributes: [:id, :game_id, :picture],
      trailers_attributes: [:id, :game_id, :youtube_link]
  end

  def admin_required
    return if current_user && (current_user.admin? || current_user.maker?)
    redirect_to root_url
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = @q.result.includes(:genres).paginate(:page => params[:page], :per_page => 9)
    @genres = Genre.all.map(&:genre)
  end

  def show
    @game = Game.find_by id: params[:id]
    if current_user.nil?
      @my_review = nil
      @other_reviews = @game.reviews
    else
      @my_review = @game.reviews.find_by user_id: current_user.id
      @other_reviews = @game.reviews.all_except current_user
    end
    @comment = unless current_user.nil?
                  @my_review || Review.new
               else
                  Review.new
               end
    @new_reply = Reply.new
  end

  private

  def game_params
    params.require(:game).permit :name, :details, :price, :picture, screenshots_attributes: [:id, :game_id, :picture]
  end
end

app/helpers/games_helper.rb
module GamesHelper
  YOUTUBE_SHORT = %r{youtu\.be\/([^\?]*)}
  YOUTUBE_LONG = %r{^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*}

  def youtube_embed youtube_url
    return unless youtube_url
    matches = YOUTUBE_SHORT.match youtube_url
    if matches
      youtube_id = matches[1]
    else
      matches = YOUTUBE_LONG.match youtube_url
      youtube_id = matches[5]
    end
    content_tag :iframe, "", src: "https://www.youtube.com/embed/#{youtube_id}",
      width: 500,
      height: 300, frameborder: 0,
      allow: "autoplay; encrypted-media", allowfullscreen: true
  end
end

app/views/games/_favorite_button.html.erb
<span id="favorite_button">
  <% if(relation = Wishlist.find_by(user_id: current_user.id, game_id: @game.id)) %>
    <%= link_to image_tag("like.png", border: 0, id: "favorite", style: 'height:30px;width:30px'), wishlist_path(relation), method: :delete, remote: true %>
  <% else %>
    <%= link_to image_tag("unlike.png", border: 0, id: "favorite", style: 'height:30px;width:30px'), wishlists_path(game_id: @game.id), method: :post, remote: true %>
  <% end %>
</span>

app/views/games/_game.html.erb
<div class="uk-width-1-3@m">
  <div class="uk-card uk-card-default">
    <div class="uk-card-media-top">
      <%= link_to game_path(game), class: "game_image-container" do %>
        <%= image_tag game.picture.url, alt: "" %>
      <% end %>
    </div>
    <div class="uk-card-body">
      <h3 class="uk-card-title">
        <%= link_to game_path(game), style: "color: #333; font-weight: bolder;" do %>
          <%= game.name %>
        <% end %>
      </h3>
      <br>
      <div id="game_detail"><%= t (".details") %>: <%= game.details %></div>
      <p><%= t (".score") %>: <%= game.score %></p>
      <p><%= t (".genre") %>:
        <% game.genres.each do |genre| %>
          <%= button_tag genre.genre, class: "search_genre" %>
        <% end %>
      </p>
      <p>
        <%= t (".price") %>:
        <% if game.price > 0 %>
          <%= "$" + game.price.to_s %>
        <% else %>
          <%= t (".free") %>
        <% end %>
      </p>
      <p><%= t (".download") %>: <%= game.download_count %></p>
    </div>
  </div>
</div>

app/views/games/index.html.erb
<div class="container uk-margin">
  <div class="uk-margin">
    <%= search_form_for @q, id: "search_form" do |f| %>
      <%= f.hidden_field :genres_genre_cont, id: "search_genres" %>
      <div class="uk-inline">
        <span class="uk-form-icon" uk-icon="icon: search"></span>
        <%= f.search_field :name_or_details_cont,
          class: "uk-input uk-form-width-medium", style: "min-width: 400px",
          placeholder: "Search name or detail" %>
      </div>
      <%= f.search_field :price_gteq, id: "search_min_price",
        class: "uk-input uk-form-width-medium", style: "width: 100px",
        placeholder: "Min price", type: "number", min: 0, pattern: "[0-9]*" %>
      <%= f.search_field :price_lteq, id: "search_max_price",
        class: "uk-input uk-form-width-medium", style: "width: 100px",
        placeholder: "Max price", type: "number", min: 0, pattern: "[0-9]*" %>
      <button type="submit" class="uk-button uk-button-default">Search</button>
    <% end %>
  </div>
  <div class="uk-grid-small uk-grid-divider uk-child-width-auto" uk-grid>
    <div>
      <ul class="uk-subnav uk-subnav-pill" uk-margin>
        <li uk-filter-control>
          <%= link_to "Clear Search", request.path %>
        </li>
      </ul>
    </div>

    <div>
      <ul class="uk-subnav uk-subnav-pill" uk-margin>
        <% @genres.each do |genre| %>
          <li><a href="#">
            <%= button_tag genre, class: "search_genre", style: "color: #999; text-decoration: none;" %>
          </a></li>
        <% end %>
      </ul>
    </div>

    <div>
      <ul class="uk-subnav uk-subnav-pill" uk-margin>
        <li><%= sort_link(@q, :name) %></li>
        <li><%= sort_link(@q, :price) %></li>
        <li><%= sort_link(@q, :score) %></li>
        <li><%= sort_link(@q, :download_count) %></li>
      </ul>
    </div>
  </div>
  <br>
  <div class="apple_pagination" style="background-color: transparent; border: none;">
    <%= will_paginate @games %>
  </div>
  <div class="uk-grid-match" uk-grid>
    <%= render @games %>
  </div>
  <div class="apple_pagination" style="background-color: transparent; border: none;">
    <%= will_paginate @games %>
  </div>
</div>

<style>
  #search_form button,
  .uk-subnav a {
    font-size: 1em !important;
  }
  #search_form button {
    color: #e5e5e5;
  }
</style>

<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
$( function() {
  var min_price_field = $("#search_min_price");
  var max_price_field = $("#search_max_price");
  $( "#slider-range" ).slider({
    range: true,
    min: 0,
    max: 200,
    values: [0, 200],
    slide: function( event, ui ) {
      $( "#amount" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] );
    }
  });
  $( "#amount" ).val( "$" + $( "#slider-range" ).slider( "values", 0 ) +
    " - $" + $( "#slider-range" ).slider( "values", 1 ) );

  $('#slider-range').slider({
    slide: function(event, ui) {
      min_price_field.val(ui.values[0]);
      max_price_field.val(ui.values[1]);
    }
  });
  $(".search_genre").click(function(){
    $("#search_genres").val($(this).text());
    $("#search_form").submit();
  });
});
</script>

app/views/games/new.html.erb
<% provide :title, t(".add_game") %>
<% provide :button_text, t(".add") %>
<% provide :url, games_path %>

<div class="uk-card uk-card-body" style="color: #fff;">
  <div class="uk-card-title">
    <h1><%= t ".add_game" %></h1>
  </div>
  <div class="uk-card-body">
    <%= render "form" %>
  </div>
</div>

app/views/games/show.html.erb
<% provide :title, @game.name %>

<div
  class="uk-height-large uk-background-cover uk-light uk-flex"
  style="background-image: url('<%= @game.picture.url %>');"
  uk-parallax="bgy: -200"
>
  <h1 class="uk-width-1-2@m uk-text-center uk-margin-auto uk-margin-auto-vertical">
  </h1>
</div>
<div class="container" id="content">
  <br><br>
  <h2 style="color: #fff">
    <%= @game.name %>
    <% unless current_user.nil? %>
      <%= render "favorite_button" %>
    <% end %>
  </h2>
  <% if !current_user.nil? && (current_user.admin? ||
    (current_user.maker? && current_user.make(@game)))%>
    <div class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <%= t ".edit" %> <b class="caret"></b>
      </a>
      <ul class="dropdown-menu">
        <li><%= link_to t(".update"), edit_admin_game_path %></li>
        <li><%= link_to t(".delete"), admin_game_path(@game), method: :delete %></li>
      </ul>
    </div>
  <% end %>
  <br><br>
  <div class="uk-grid">
    <div class="uk-width-1-3@m">
      <h4 style="color: #fff; text-align: left;">
        <%= t (".info") %>: <%= @game.details %>
      </h4>
      <br>
      <h4 style="color: #fff; text-align: left;">
        <%= t (".price") %>:
        <% if @game.price > 0 %>
          <%= "$" + @game.price.to_s %>
        <% else %>
          <%= t (".free") %>
        <% end %>
      </h4>
      <br>
      <h4 style="color: #fff; text-align: left;">
        <%= t (".genre") %>:
        <span style="color: #fff; text-align: left;">
          <% @game.genres.each do |genre| %>
            <%= genre.genre %>
          <% end %>
        </span>
      </h4>
      <br>
      <h4 style="color: #fff; text-align: left;">
        <%= t (".avg_score") %>:
        <div
          id="score_ruby_var"
          data-comment_score="0"
          data-score="<%= @game.score %>"
          data-max_score="<%= Settings.max_score %>">
        </div>
        <div class="wthreeratingaits" id="game_star" style="margin-top: 5px;">
          <%= render "shared/star", score: @game.score %>
        </div>
      </h4>
    </div>
    <div class="uk-width-expand@m">
      <div uk-slider>
        <div class="uk-position-relative uk-visible-toggle uk-light">
          <ul class="uk-slider-items uk-child-width-1-2 uk-child-width-1-3@s uk-child-width-1-4@m">
            <% @game.screenshots.each.with_index(1) do |screenshot, index| %>
              <li>
                <div uk-lightbox>
                  <%= link_to screenshot.picture.url, class: "game_image-container" do %>
                    <%= image_tag screenshot.picture.url, alt: "Game Robo" %>
                  <% end %>
                </div>
              </li>
            <% end %>
          </ul>
          <a class="uk-position-center-left uk-position-small uk-hidden-hover" href="#" uk-slidenav-previous uk-slider-item="previous"></a>
          <a class="uk-position-center-right uk-position-small uk-hidden-hover" href="#" uk-slidenav-next uk-slider-item="next"></a>
        </div>
        <ul class="uk-slider-nav uk-dotnav uk-flex-center uk-margin"></ul>
      </div>
    </div>
  </div>
</div>

<% @game.trailers.each do |trailer| %>
  <%= youtube_embed trailer.youtube_link %>
<% end %>

<div>
  <br>
  <br>
  <div class="uk-card uk-card-default uk-card-body">
    <div class="container">
      <div style="font-size: 1.1em; color: #333; margin-top: 20px;">
        <h3 id="review_count"><%= t ".reviews" %> (<%= @game.reviews.size %>)</h3>
        <ul class="uk-list uk-list-divider">
          <li>
            <div id="comment_area">
              <% if logged_in? && !had_comment_in(@game) %>
                <%= render "reviews/comment", game_id: @game.id %>
              <% end %>
            </div>
          </li>
        </ul>
        <ul id="reviews" class="uk-list uk-list-divider">
          <%= render "reviews/sorted_review",
                        my_review: @my_review, other_reviews: @other_reviews %>
        </ul>
      </div>
    </div>
  </div>
</div>

<!-- Popup-Box-JavaScript -->
<script src="/assets/jquery.chocolat.js"></script>
<script type="text/javascript">
  $(function() {
    $('.w3portfolioaits-item a').Chocolat();
  });
</script>
<!-- //Popup-Box-JavaScript -->